name: dataease
services:
  mysql:
    image: mariadb:10.6
    container_name: dataease-mysql
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MARIADB_DATABASE: dataease
      MARIADB_ROOT_PASSWORD: nu4x599Wq7u0Bn8EABh3J91G
    volumes:
      - type: bind
        source: /DATA/AppData/dataease/mysql
        target: /var/lib/mysql
    networks:
      - dataease

  dataease:
    image: wojiushixiaobai/dataease:latest
    container_name: dataease
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: dataease
      DB_USER: root
      DB_PASSWORD: nu4x599Wq7u0Bn8EABh3J91G
    ports:
      - target: 8100
        published: "8101"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dataease/core/data
        target: /opt/dataease2.0/data
      - type: bind
        source: /DATA/AppData/dataease/core/data/geo
        target: /opt/dataease2.0/data/geo
      - type: bind
        source: /DATA/AppData/dataease/core/logs
        target: /opt/dataease2.0/logs
      - type: bind
        source: /DATA/AppData/dataease/core/cache
        target: /opt/dataease2.0/cache
    networks:
      - dataease
    deploy:
      resources:
        reservations:
          memory: 1024M

networks:
  dataease:
    name: dataease

x-casaos:
  architectures:
    - amd64
    - arm64
  main: dataease
  store_app_id: dataease
  author: Cp0204
  category: Analytics
  description:
    en_us: DataEase is an open-source free data visualization analysis tool, Aiming to help users with various levels of technical skills to carry out data analysis quickly, and explore the value of data easily.
    zh_cn: DataEase 是开源的数据可视化分析工具，帮助用户快速分析数据并洞察业务趋势，从而实现业务的改进与优化。DataEase 支持丰富的数据源连接，能够通过拖拉拽方式快速制作图表，并可以方便的与他人分享。
  developer: dataease
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/dataease/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/dataease/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/dataease/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/dataease/screenshot-3.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/dataease/screenshot-4.png
  tagline:
    en_us: An open-source free data visualization analysis tool.
    zh_cn: 人人可用的开源 BI 工具
  # thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/dataease/thumbnail.png
  tips:
    before_install:
      en_us: |
        username: admin
        password: DataEase@123456
      zh_cn: |
        用户名: admin
        密码: DataEase@123456
  title:
    en_us: DataEase
  port_map: "8101"
