name: flare
services:
  flare:
    image: soulteary/flare:latest
    deploy:
      resources:
        reservations:
          memory: 32M
    network_mode: bridge
    ports:
      - target: 5005
        published: "5005"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/flare
        target: /app
    container_name: flare

x-casaos:
  architectures:
    - arm
    - arm64
    - amd64
  main: flare
  store_app_id: flare
  author: Cp0204
  category: WEB
  description:
    en_us: A lightweight, fast, and beautiful personal start page for your home lab, self-hosted services, and more.
    zh_cn: 轻量、快速、美观的个人导航页，适用于 HomeLab 或其他注重私密的场景。
  developer: soulteary
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/flare/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/flare/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/flare/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/flare/screenshot-3.png
  tagline:
    en_us: A self-hosted startpage for your server.
    zh_cn: 自托管的浏览器起始页。
  title:
    en_us: Flare
  index: /
  port_map: "5005"
